### ISSUE TITLE
Design issue on Chromium 53

### ISSUE THREAD

**Issue by bzg** [bayesimpact/bob-emploi#2] opened 2016-11-25 10:05 UTC
Congrats for https://www.bob-emploi.fr!

The display of the top bar looks wrong on Chromium Version 53.0.2785.143 Built on Ubuntu, running on Ubuntu 16.04. See below:

![bob-emploi-display-chromium](https://cloud.githubusercontent.com/assets/63500/20621447/d69fd86c-b2fe-11e6-8cf8-5e11a30f5d91.png)

No plugin is activated. The display is fine on Firefox 50 though.

**Comment by pcorpet** [comment] 2016-11-25 13:06
Thanks for reporting. I'm installing Chromium to try it on my ubuntu machine. For now I have not been able to reproduce on other browsers.

**Comment by pcorpet** [comment] 2016-11-25 13:27
I was able to reproduce and really think this is due to https://github.com/FormidableLabs/radium/issues/818. I'll follow up on how we can fix it on our side.

**Comment by bzg** [comment] 2016-11-25 14:07
Thanks in advance!

**Comment by pcorpet** [comment] 2016-11-28 17:51
Fixed in prod.

**Closed by pcorpet** 2016-11-28 17:51 UTC

**Comment by bzg** [comment] 2016-11-28 18:53
I confirm it looks fine now, thank you!
